version: '3.4'

services:

  # USE LIBRECHAT CONFIG FILE
  api:
    build:
      context: .
      dockerfile: Dockerfile.custom   # this line
    image: librechat-custom
    volumes:
    - type: bind
      source: ./librechat.yaml
      target: LOCAL/PATH/TO/LibreChat/librechat.yaml

  # DISABLE MEILISEARCH
  meilisearch:
    profiles:
      - donotstart

  # USE RAG API IMAGE WITH LOCAL EMBEDDINGS SUPPORT
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest

networks:
  librechat_default:
    external: true